export const lista_dados1 = [
    { id:'0', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'1', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'2', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'3', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'4', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'5', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'6', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'7', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'8', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'9', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'10', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'11', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'12', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'13', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'14', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'15', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'16', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'17', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'18', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'19', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'20', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'21', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'22', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'23', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'24', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'25', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'26', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'27', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'28', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'29', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'30', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
    { id:'31', imagem: '[Imagem]', nome: 'M4 Sherman', paisOrigem: 'EUA', tipo: 'Carro de combate Médio' },
];

export const lista_dados2 = [
    { 
        id:'0',
        imagem: '[Imagem]',
        nome: 'M4 Sherman',
        paisOrigem: 'EUA',
        tipo: 'Carro de combate médio',
        fabricante: 'American Locomotive Company',
        utilizadores: 'EUA',
        quantidadeProduzida: '49,234',
        peridoServico: '1942–1957',
        massa: '30.3 Toneladas',
        comprimento: '5.84 m',
        altura: '2.74 m',
        largura: '2.62 m',
        tripulacao: '5',
        custoUnitario: '44.556 dólares',
        armamento: 'Canhão 75 mm gun M3 e metralhadora .50 Browning M2HB',
    },
];